# Generated by Django 5.1.2 on 2025-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standingtime',
            name='time',
            field=models.FloatField(max_length=20),
        ),
    ]
