# Generated by Django 5.2.4 on 2025-10-18 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_standingtime_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('state', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='standingtime',
            name='time',
            field=models.FloatField(),
        ),
    ]
